namespace ExpenseTracker.API.Models;

/// <summary>
/// A notification generated by the system for the user.
/// Alerts are created automatically by the budget service and anomaly detection service.
/// </summary>
public class Alert
{
    public int Id { get; set; }
    public int UserId { get; set; }

    /// <summary>The transaction that triggered this alert. Null for budget-only alerts.</summary>
    public int? TransactionId { get; set; }

    /// <summary>
    /// Alert type — used by the frontend to display the correct icon and color.
    /// Values: "BudgetWarning" (80% reached), "BudgetExceeded" (100%+),
    ///         "Anomaly" (unusual transaction), "NewMerchant".
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>Human-readable alert message displayed to the user.</summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>False until the user dismisses/reads the alert. Used for notification badge count.</summary>
    public bool IsRead { get; set; } = false;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // --- Navigation ---
    public User User { get; set; } = null!;
    public Transaction? Transaction { get; set; }
}
